sudo: false

language: python

matrix:
  include:
    - python: 2.7
      env: REQ_FILE = "./ci/min_reqs.txt"
    - python: 2.7
      env: REQ_FILE = "./ci/reqs.txt"
    - python: 3.6
      env: REQ_FILE = "./ci/min_reqs.txt"
    - python: 3.6
      env: REQ_FILE = "./ci/reqs.txt"

before_install:
  - pip install -r $REQ_FILE

install:
  - pip install .

script:
  - tests/run_tests
