sudo: false

language: python

python:
  - "2.7"
  - "3.6"

# Test two environments:
# 1) dependencies with pinned versions from requirements.txt
# 2) 'pip install --upgrade --upgrade-strategy=eager .' to install upgraded
#    dependencies from PyPi using version ranges defined within setup.py
env:
  - REQ_ENV='-r requirements.txt'
  - REQ_ENV='--upgrade --upgrade-strategy=eager .'

install:
  - pip install $REQ_ENV

script:
  - tests/run_tests
